[package]
name = "static_hashmap_2015"
version = "0.1.0"
authors = ["Akson <Akson.L@outlook.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
