[package]
name = "working_with_tarballs"
version = "0.1.0"
authors = ["Akson <Akson.L@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.20"
tar = "0.4.33"
