[package]
name = "r2d2_demo"
version = "0.1.0"
authors = ["Akson <Akson.L@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8.3"
r2d2_postgres = "0.14.0"
