[package]
name = "my_app"
version = "0.1.0"
authors = ["Akson <Akson.L@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log4rs = "0.8.0"
log = "0.4"
my_lib = {path = "../my_lib"}